import type { Region, Artist, ArtItem } from '@/types';

const img = (seed: string, w = 600, h = 400) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const regions: Region[] = [
  { id: 'r1', name: 'Oaxaca, Mexico', shortHistory: 'Cradle of indigenous art.', culturalSignificance: 'Alebrijes, pottery, textiles.', heroImage: img('oaxaca', 1200, 600), tags: ['textiles', 'pottery'] },
  { id: 'r2', name: 'Bali, Indonesia', shortHistory: 'Temple and court art.', culturalSignificance: 'Wood carving, silver.', heroImage: img('bali', 1200, 600), tags: ['woodcarving', 'silver'] },
  { id: 'r3', name: 'Marrakech, Morocco', shortHistory: 'Berber and Andalusian crossroads.', culturalSignificance: 'Zellige, leather.', heroImage: img('marrakech', 1200, 600), tags: ['ceramics', 'leather'] },
  { id: 'r4', name: 'Kyoto, Japan', shortHistory: 'Imperial capital craftsmanship.', culturalSignificance: 'Lacquer, ceramics.', heroImage: img('kyoto', 1200, 600), tags: ['ceramics', 'lacquer'] },
  { id: 'r5', name: 'Himachal Pradesh, India', shortHistory: 'Nestled in the Himalayas, Himachal has been a cradle of Pahari miniature painting since the 17th century. The Kangra, Guler, and Basohli schools flourished under royal patronage.', culturalSignificance: 'Pahari miniatures, Kangra paintings depicting Radha-Krishna and Himalayan landscapes. Natural pigments on paper and cloth. Lyrical, romantic themes rooted in devotion and nature.', heroImage: img('himachal', 1200, 600), tags: ['painting', 'miniature', 'pahari', 'kangra'] },
];

export const artists: Artist[] = [
  { id: 'a1', name: 'Elena Martinez', photoUrl: img('elena', 200, 200), regionId: 'r1', bio: 'Fourth-generation artisan.', story: 'I learned from my grandmother.', verified: true, socialLinks: [{ platform: 'instagram', url: '#' }], joinedDate: '2022-03-15' },
  { id: 'a2', name: 'Wayan Sutra', photoUrl: img('wayan', 200, 200), regionId: 'r2', bio: 'Balinese woodcarver.', story: 'My father taught me.', verified: true, socialLinks: [{ platform: 'instagram', url: '#' }], joinedDate: '2021-11-20' },
  { id: 'a3', name: 'Fatima Alaoui', photoUrl: img('fatima', 200, 200), regionId: 'r3', bio: 'Marrakech ceramist.', story: 'I work in the medina.', verified: true, socialLinks: [{ platform: 'instagram', url: '#' }], joinedDate: '2023-01-10' },
  { id: 'a4', name: 'Kenji Tanaka', photoUrl: img('kenji', 200, 200), regionId: 'r4', bio: 'Kyoto potter.', story: 'Imperfection is beauty.', verified: true, socialLinks: [{ platform: 'instagram', url: '#' }], joinedDate: '2020-06-01' },
  { id: 'a5', name: 'Priya Thakur', photoUrl: img('priya', 200, 200), regionId: 'r5', bio: 'Third-generation Pahari painter from Kangra Valley. Trained in the classical Kangra style by her grandmother.', story: 'I grew up watching my grandmother paint Radha and Krishna on silk. The mountains and rivers of Himachal flow through every stroke. I use stone pigments and brushes made from squirrel hair, just as our ancestors did.', verified: true, socialLinks: [{ platform: 'instagram', url: '#' }], joinedDate: '2022-08-12' },
];

export const artItems: ArtItem[] = [
  { id: 'art1', title: 'Jaguar Spirit Alebrije', price: 450, currency: 'USD', images: [img('art1', 800, 800)], regionId: 'r1', artistId: 'a1', style: 'Traditional', medium: 'Wood', dimensions: '28 x 18 cm', yearCreated: 2023, story: 'The jaguar represents strength.', significance: ['Protection'], technique: 'Hand-carved', materials: 'Copal wood', tags: ['alebrije'], availability: 'IN_STOCK', shippingFrom: 'Oaxaca', etaDays: 14, popularityScore: 95, createdAt: '2023-09-01' },
  { id: 'art2', title: 'Rangda Mask', price: 680, currency: 'USD', images: [img('art2', 800, 800)], regionId: 'r2', artistId: 'a2', style: 'Traditional', medium: 'Wood', dimensions: '45 x 35 cm', yearCreated: 2023, story: 'Rangda is the queen of demons.', significance: ['Balance'], technique: 'Relief carving', materials: 'Suar wood', tags: ['mask'], availability: 'LIMITED', shippingFrom: 'Bali', etaDays: 21, popularityScore: 88, createdAt: '2023-07-15' },
  { id: 'art3', title: 'Zellige Mosaic Plate', price: 320, currency: 'USD', images: [img('art3', 800, 800)], regionId: 'r3', artistId: 'a3', style: 'Geometric', medium: 'Ceramic', dimensions: '40 cm', yearCreated: 2024, story: 'Eight-pointed star pattern.', significance: ['Islamic geometry'], technique: 'Hand-cut zellige', materials: 'Ceramic', tags: ['zellige'], availability: 'IN_STOCK', shippingFrom: 'Marrakech', etaDays: 18, popularityScore: 92, createdAt: '2024-01-05' },
  { id: 'art4', title: 'Raku Tea Bowl', price: 580, currency: 'USD', images: [img('art4', 800, 800)], regionId: 'r4', artistId: 'a4', style: 'Wabi-sabi', medium: 'Raku', dimensions: '12 cm', yearCreated: 2023, story: 'Fired in a single day.', significance: ['Tea ceremony'], technique: 'Raku firing', materials: 'Raku clay', tags: ['raku'], availability: 'IN_STOCK', shippingFrom: 'Kyoto', etaDays: 21, popularityScore: 90, createdAt: '2023-11-20' },
  { id: 'art5', title: 'Owl Messenger Alebrije', price: 380, currency: 'USD', images: [img('art5', 800, 800)], regionId: 'r1', artistId: 'a1', style: 'Traditional', medium: 'Wood', dimensions: '22 cm', yearCreated: 2023, story: 'The owl is a messenger.', significance: ['Wisdom'], technique: 'Hand-carved', materials: 'Copal wood', tags: ['alebrije'], availability: 'IN_STOCK', shippingFrom: 'Oaxaca', etaDays: 14, popularityScore: 82, createdAt: '2023-10-10' },
  { id: 'art6', title: 'Barong Spirit Sculpture', price: 520, currency: 'USD', images: [img('art6', 800, 800)], regionId: 'r2', artistId: 'a2', style: 'Traditional', medium: 'Wood', dimensions: '35 cm', yearCreated: 2023, story: 'Barong represents good.', significance: ['Protection'], technique: 'Full-round carving', materials: 'Suar wood', tags: ['barong'], availability: 'IN_STOCK', shippingFrom: 'Bali', etaDays: 21, popularityScore: 85, createdAt: '2023-08-01' },
  { id: 'art7', title: 'Radha-Krishna in the Grove', price: 890, currency: 'USD', images: [img('kangra1', 800, 800)], regionId: 'r5', artistId: 'a5', style: 'Kangra Miniature', medium: 'Natural pigments on silk', dimensions: '25 x 20 cm', yearCreated: 2024, story: 'This piece follows the classical Kangra tradition—lyrical, soft colors, flowing lines. Radha and Krishna in a grove by the Beas River, surrounded by lotus and mango trees. I ground lapis lazuli, malachite, and cinnabar by hand for the pigments, and used a squirrel-hair brush passed down in my family.', significance: ['Bhakti devotion', 'Romantic lyricism', 'Himalayan landscape'], technique: 'Kangra miniature painting', materials: 'Silk, stone pigments (lapis, malachite, cinnabar), gold leaf', tags: ['kangra', 'pahari', 'miniature', 'radha-krishna'], availability: 'IN_STOCK', shippingFrom: 'Kangra, Himachal Pradesh', etaDays: 21, popularityScore: 91, createdAt: '2024-02-01' },
  { id: 'art8', title: 'Raja Sansar Chand at Sunset', price: 720, currency: 'USD', images: [img('kangra2', 800, 800)], regionId: 'r5', artistId: 'a5', style: 'Pahari', medium: 'Natural pigments on paper', dimensions: '30 x 22 cm', yearCreated: 2023, story: 'A tribute to the great patron of Kangra art, Raja Sansar Chand. The Dhauladhar range rises behind him as he surveys his kingdom at twilight. This piece draws from Guler influences—bold yet delicate, with the characteristic Pahari palette of earth and jewel tones.', significance: ['Royal patronage', 'Mountain kingdom', 'Cultural heritage'], technique: 'Pahari miniature, stone pigments', materials: 'Handmade paper, stone pigments, gold', tags: ['pahari', 'kangra', 'miniature', 'himachal'], availability: 'IN_STOCK', shippingFrom: 'Kangra, Himachal Pradesh', etaDays: 21, popularityScore: 87, createdAt: '2023-12-15' },
  { id: 'art9', title: 'Gopis by the Yamuna', price: 650, currency: 'USD', images: [img('kangra3', 800, 800)], regionId: 'r5', artistId: 'a5', style: 'Kangra Miniature', medium: 'Natural pigments on cotton', dimensions: '28 x 18 cm', yearCreated: 2023, story: 'The gopis gather by the river, their flowing dupattas echoing the waves. A beloved theme in Pahari art—devotion, longing, and the beauty of the Himalayan foothills. Painted in the soft greens and pinks of monsoon in the valley.', significance: ['Devotional narrative', 'Feminine grace', 'Nature and spirit'], technique: 'Kangra miniature, layering', materials: 'Cotton cloth, stone pigments, vegetable dyes', tags: ['kangra', 'pahari', 'gopis', 'miniature'], availability: 'LIMITED', shippingFrom: 'Kangra, Himachal Pradesh', etaDays: 21, popularityScore: 84, createdAt: '2023-10-20' },
  { id: 'art10', title: 'Devi-Devta Rath Yatra Procession', price: 780, currency: 'USD', images: ['/himachali-procession.png'], regionId: 'r5', artistId: 'a5', style: 'Traditional Himachali Folk', medium: 'Natural pigments on cloth', dimensions: '45 x 35 cm', yearCreated: 2024, story: 'This painting captures a sacred procession from the hills of Himachal—devotees in traditional white attire and Himachali caps carry the deity\'s palanquin, accompanied by the sound of horns and drums. The red ceremonial object adorned with golden motifs represents the presence of the divine. A woman claps in devotion while the mountains watch over the ritual. Such processions, known as Devi-Devta Rath Yatra, connect our villages to the gods who dwell in these peaks.', significance: ['Sacred procession', 'Cultural heritage', 'Mountain devotion'], technique: 'Traditional folk painting, flat color with clear outlines', materials: 'Cloth, natural pigments, vegetable dyes', tags: ['himachal', 'procession', 'folk', 'devotional'], availability: 'IN_STOCK', shippingFrom: 'Kangra, Himachal Pradesh', etaDays: 21, popularityScore: 93, createdAt: '2024-03-01' },
];
